apiVersion: v1
kind: Pod
metadata:
  name: configmap-access
spec:
  containers:
  - name: centos
    image: centos
    command: ["/bin/sh","-c","while : ;do cat /src/app/config/application.properties; sleep 10; done"]
    volumeMounts:
     - name: config-volume
       mountPath: /src/app/config
  volumes:
   - name: config-volume
     configMap: 
       name: example