apiVersion: v1
kind: Pod
metadata:
  name: clusterip-check
spec:
  containers:
    - name: centos
      image: centos
      command: ["/bin/bash", "-c", "while : ;do curl http://${NGINX_SERVICE_HOST}:80/; sleep 10; done"]