apiVersion: v1
kind: Pod
metadata:
  name: microservice
spec:
  containers:
   - name: microservice
     image: rieckpil/microservice
     readinessProbe:
      httpGet:
        path: /health
        port: 8080
      periodSeconds: 5
      initialDelaySeconds: 10
      successThreshold: 2
      failureThreshold: 3
      timeoutSeconds: 1