apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx-pod
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "foo.local"
            - "bar.local"
        - ip: "10.1.2.3"
          hostnames:
            - "foo.remote"
            - "bar.remote"
      containers:
        - name: nginx
          image: nginx:1.7.9
          env:
            - name: SECRET_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: username
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: password
            - name: DUKE
              value: JAVA_11
          resources:
            requests:
              cpu: 0.1
              memory: 128M
            limits:
              cpu: 0.2
              memory: 256M
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cache-vol
              mountPath: /cache
            - name: mysecrets
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: cache-vol
          emptyDir: {}
        - name: mysecrets
          secret:
            secretName: mysecret
            defaultMode: 256
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 80