apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-spring-boot-java-microservice-deployment
spec:
  selector:
    matchLabels:
      app: simple-spring-boot-java-microservice
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    spec:
      containers:
      - name: simple-spring-boot-java-microservice
        image: simple-spring-boot-java-microservice:latest
        ports:
        - containerPort: 8080